### ISSUE TITLE
breaks on clean install; because the db directory does not exists

### ISSUE THREAD

**Issue by jadijadi** [ekm507/makenote#5]
```
jadi@funlife ~/makenote (master) [1]> makenote first run
Traceback (most recent call last):
  File "/opt/homebrew/bin/makenote", line 6, in <module>
    from makenote import cli
  File "/opt/homebrew/lib/python3.11/site-packages/makenote/cli.py", line 29, in <module>
    migrate_if_needed(config_filename)
  File "/opt/homebrew/lib/python3.11/site-packages/makenote/convert_old_db_to_new.py", line 144, in migrate_if_needed
    convert_diaryFile(diaryFileDir)
  File "/opt/homebrew/lib/python3.11/site-packages/makenote/convert_old_db_to_new.py", line 130, in convert_diaryFile
    if 'diaryFile.db' in os.listdir(database_directory):
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jadi/.local/share/makenote/databases'
```

Should check the existence of the directory first and create it if not exists.

**Comment by ekm507** [comment]
Hi,
thank you for this issue.
I added a commit to fix it.
will you please check this once again?

**Comment by ekm507** [comment]
Hi,
thanks for bug report.
I believe that it must be fixed by now.
will you please check it once again?
